version: '3.8'

services:
  # Serviço do Banco de Dados MySQL
  mysql-db:
    image: mysql:8.0
    container_name: localibrary-mysql
    # Lê as variáveis do arquivo .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"
    volumes:
      - ./db_localibrary.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço da API Spring Boot
  localibrary-api:
    container_name: localibrary-api
    build: .
    ports:
      - "8080:8080"
    # Passa as variáveis do .env para dentro do container Java
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:3000}
    depends_on:
      mysql-db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads

volumes:
  db-data: